### ISSUE TITLE
Leaked Slack Token

### ISSUE THREAD

**Issue by heyvito** [yeokm1/w31slack#1]
Hi there! I'd like to congratulate you for the job done here! It's awesome to see something being built for such an ancient OS!

I'd just like to leave a heads-up that a Slack API token [is still present](
https://github.com/yeokm1/w31slack/blob/master/app/w31slack.ini#L1) [in your sources](https://github.com/yeokm1/w31slack/blob/master/release/w31slack.ini#L1), so in case you didn't, please revoke it. ✨

**Comment by yeokm1** [comment]
Thanks!
I understand that. :) The token is already revoked.

I deliberately left it there so whoever uses my code will know where to place their tokens.

**Comment by heyvito** [comment]
Awesome! I just decided to give a heads-up in case you left if by accident! Better safe than sorry. :D

Best wishes!
