### ISSUE TITLE
Windows 3.11 WFW image ???

### ISSUE THREAD

**Issue by borrougagnou** [yeokm1/w31slack#4]
Hello !
I would like to know, where-are you found your
VM Windows 3.11 WFW with network support ???

Because each time I try to create my own VM with Windows 3.11 something don't work
so if you can help me I wont refuse ^^.

Regards,
borrougagnou

**Comment by yeokm1** [comment]
Hi, you can follow this guide. https://socket3.wordpress.com/2016/08/25/install-configure-ms-dos-6-22-and-windows-3-1-using-oracle-virtualbox/

I used it personally and it worked.

**Comment by mylittlefilly** [comment]
Okay, thanks!
Because you make me an idea and I want to do the same thing with discord :p

**Comment by borrougagnou** [comment]
Okay, thanks !

Because you make me an idea and I want to do the same thing with discord ! :p

**Comment by yeokm1** [comment]
Sure go ahead! I'll want to hear about it when you are ready to share!
